apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: shopping/inventory-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopping-config
                  key: EUREKA_HOST
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopping-config
                  key: MONGODB_HOST
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: shopping-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopping-secrets
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 25
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: shopping
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8083
      targetPort: 8083
