apiVersion: v1
kind: Secret
metadata:
  name: shopping-secrets
  namespace: shopping
type: Opaque
stringData:
  POSTGRES_PASSWORD: secret
  DB_PASSWORD: secret
  JWT_SECRET: change-me-in-prod-this-is-a-long-demo-secret-key-256bits-minimum-len
